#!/usr/bin/env python3

# TODO
import nltk
import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    text = helpers.get_user_timeline(sys.argv[1])
    if len(text) == 0:
        sys.exit("No tweets for now here.")
    # analyze tweet
    for i in range(len(text)):
        score = analyzer.analyze(text[i])[0]
        if score > 0.0:
            print(colored("{} {}".format(score, text[i]), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, text[i]), "red"))
        else:
            print(colored("{} {}".format(score, text[i]), "yellow"))

if __name__ == "__main__":
    main()
